### ISSUE TITLE
There is no renderDetail function defined!

### ISSUE THREAD

**Issue by shubhamverma27** [Johan-dutoit/react-native-timeline-feed#10]
I am migrating from react native listview timeline but am unable to use render detail in this component.
there is no definition for renderDetail here

**Comment by Johan-dutoit** [comment]
What version of this library have you installed?

**Comment by Johan-dutoit** [comment]
Hmm you'd want to pin to version 1.0.1 instead, that will result in the what you are looking for.
2.0.0 is still in alpha and is breaking change, when migrating from the listview.

**Comment by Johan-dutoit** [comment]
I've also tagged version 1.0.1 as the latest/stable version.
