### ISSUE TITLE
How can i custom Timeline.Line in dotted or dashed line instead of solid line ?

### ISSUE THREAD

**Issue by leminhtuanlc92** [Johan-dutoit/react-native-timeline-feed#14]
![Screen Shot 2019-09-04 at 10 47 15 AM](https://user-images.githubusercontent.com/34678201/64224375-723c9280-cf01-11e9-8c0a-4e7072590e47.png)
line this

**Comment by leminhtuanlc92** [comment]
Nevemind, I found a solution

**Comment by ghost** [comment]
@leminhtuanlc92 Hi, can you share your solution please? I was looking for something similar.
