### ISSUE TITLE
Override lineColor props is not working

### ISSUE THREAD

**Issue by naytun** [Johan-dutoit/react-native-timeline-feed#5]
H,
I appreciate your attempt to upgrade Timeline with "FlatList". 
When I try to override lineColor in my view it is not working. Both lineColor and dotColor are using the default colors. Thanks.

**Comment by Johan-dutoit** [comment]
Thanks for reporting this.
A new version (1.0.1) has now been released and addresses this.

**Comment by naytun** [comment]
Thank you @Johan-dutoit . You made my day!
