### ISSUE TITLE
VirtualizedList missing keys for items warning

### ISSUE THREAD

**Issue by firehand33** [Johan-dutoit/react-native-timeline-feed#8]
Hi,

I'm getting this warning, "VirtualizedList: missing keys for items, make sure to specify a key property on each item or provide a custom keyExtractor."""

Version:
"react-native-timeline-feed": "^1.0.1",
"react-native": "^0.57.8",

**Comment by Johan-dutoit** [comment]
Hi,

If your data data have a `key` property on each item, then you need to pass in a `keyExtractor` function.  This is a `FlatList` requirement (see: https://facebook.github.io/react-native/docs/flatlist#keyextractor)
